export const COMPANY = {
  name: "Myers Underground Utilities, LLC",
  shortName: "Myers Underground",
  phone: "(601) 544-4188",
  phoneHref: "tel:+16015444188",
  fax: "(601) 544-4189",
  email: "myersunderground@att.net",
  emailHref: "mailto:myersunderground@att.net",
  address: "408 Ryan Road, Hattiesburg, Mississippi 39401",
  addressShort: "408 Ryan Road, Hattiesburg, MS 39401",
  mapQuery: "408+Ryan+Road,+Hattiesburg,+MS+39401",
  serviceArea: "Mississippi & Alabama",
};

export const SERVICES = [
  "Water",
  "Sanitary Sewer",
  "Fire Protection Systems",
  "Force Mains",
  "Ground Water Storage Tanks",
  "Water Treatment Plants",
  "Sewage Pumping Stations",
  "Rural Water Systems",
  "Storm Drainage & Structures",
  "Road Building",
  "Site Work",
  "Clearing & Grubbing",
  "Boring & Tunneling",
];

export const TESTIMONIALS = [
  {
    quote:
      "I appreciate the fine work you and your crew performed while relocating a 10\" HDPE force main from an existing bridge that was scheduled for replacement. You had to perform this work in a way to minimize the downtime on the existing force main, which went very smoothly.",
    name: "Edward L. (Ned) Hogg, P.E.",
    company: "Seymour Engineering",
  },
  {
    quote:
      "We've been working with Myers Underground Utilities over the course of the past several years in several different types of work. They performed the work in the most professional manner possible. We would recommend them for any work related to their field of experience.",
    name: "Kyle D. Wallace, P.E.",
    company: "VP, Shows, Dearmon & Waits, Inc.",
  },
  {
    quote:
      "Our relationship with Myers Underground has been entirely satisfactory. Myers Underground is a well respected company that does quality work and completes projects on schedule. We are proud to have them as a sub-contractor, and look forward to doing business with them for many years to come.",
    name: "Arthur Henderson",
    company: "Hub Mechanical Contractors, Inc.",
  },
];

export const PROJECT_CATEGORIES = [
  {
    id: "municipal",
    name: "Municipal & Public Works",
    blurb: "City water and sewer systems, CDBG projects, pump stations, and regional infrastructure.",
    highlights: [
      "Sewerage Improvements — City of Petal",
      "Pump Station & Force Main — City of Laurel",
      "Sanitary Sewer Replacement & Repair — Lumberton, MS",
      "Waste Water Treatment Facility — Walthall City",
      "Water Main Installation — City of Picayune",
      "Sewage Treatment Project — Pine Belt Airport",
    ],
  },
  {
    id: "commercial",
    name: "Commercial & Institutional",
    blurb: "Retail, healthcare, education, and government facility utilities.",
    highlights: [
      "Walmart Super Center — Wiggins, MS",
      "Site Utilities for Petal Walmart",
      "Forrest General Hospital — Sewer Crossing & ED/ICU Addition",
      "Additions & Renovations — Forrest County Agricultural High School",
      "Parking, Drainage & Sewer Improvements — JCJC",
      "Dept. of Mental Health — South Psychiatric Hospital",
    ],
  },
  {
    id: "subdivisions",
    name: "Subdivisions & Residential",
    blurb: "Full utility infrastructure for new neighborhoods and residential developments.",
    highlights: [
      "Woods Subdivision Phase I — Lamar City",
      "West Lake Manor Second Addition — Lamar Park Water Assoc.",
      "Oak Hill Subdivision Phase I",
      "Bellcrest Mobile Home Village Phase II",
      "Crest Mobile Home Village — Forrest City",
      "Comer Oaks — Leon Perry",
    ],
  },
  {
    id: "industrial",
    name: "Industrial",
    blurb: "Manufacturing, energy, and military installations across the Gulf South.",
    highlights: [
      "Cooper Power Systems Expansion — Lumberton, MS",
      "Dart Container Corp. — Fire Protection",
      "Nordan Smith Welding — Generation, Production & Distribution Complex",
      "Camp Shelby — Lee Ave. Upgrades, MS National Guard",
      "Sunbeam — Fire Protection",
      "RV Parking & Utilities — Purvis Industrial Park",
    ],
  },
] as const;

export const ALL_PROJECTS = [
  "Commercial Development for Lamar Park Water and Sewer Association",
  "Additions & Renovations to Forrest County Agricultural High School",
  "CDBG #97-037-ED-1F02 Cooper Power Systems Expansion, Lumberton, MS",
  "CDBG #7-074-EM-1 & #6-074-EM-97 Salem Attendance Center, Walthall City",
  "Sanitary Sewer Relocation, Summit, MS",
  "Pump Station Rehabilitation, Purvis, MS",
  "Crest Mobile Home Village, Forrest City",
  "Dept. of Mental Health South Psychiatric Hospital",
  "Forrest City Tax Services Building Drainage",
  "Family Center Phase I — West Campus Sewer Layout",
  "Relocation of HWY 45 Water Utility",
  "Water Line Extension Project",
  "Sewerage Improvements, City of Petal",
  "Yard Piping Modifications, City of Petal",
  "Comer Oaks, Leon Perry",
  "Fire Protection Water System, Lauderdale",
  "Pump Station Rehabilitation, City of Purvis",
  "Carson Water Association",
  "Walmart Super Center, Wiggins, MS",
  "Town of Prentiss Water Association",
  "Sewer Main Addition CDBG #6-039-EDIF-01, Lamar County BOS",
  "Water Main Installation, City of Picayune",
  "HWY 57 Utility, Town of McLain",
  "Water System Improvements, Carson Water Association",
  "Sanitary Sewer Replacement & Repair, Lumberton, MS",
  "Waste Water Treatment Facility, Walthall City",
  "8\" Water Main Extension, SE Greene Water Authority",
  "Replacement of Existing Sewer Lines, MS Housing Project",
  "RV Parking & Utilities Addition, Purvis Industrial Park",
  "8\" Sewer Main & 6\" Water Main, City of Petal",
  "CDBG #9-1129-310-UN-01 Dosing Basin Repair",
  "Sunbeam Fire Protection",
  "Waterline Extension Project, SW Covington Water Association",
  "Dart Container Corp. Fire Protection",
  "Woods Subdivision Phase I, Lamar City",
  "Parking Addition with Roadway, Drainage & Sewer Improvements, JCJC",
  "State HWY Project Water Mains & Services, West Lamar Water Association",
  "Forrest General Hospital Sewer Crossing",
  "Pump Station and Force Main, City of Laurel",
  "Water Line Relocation, City of Petal",
  "Dosing Basin Repair, City of Purvis",
  "Schools, Lamar County BOS",
  "Upgrades to Lee Ave., Camp Shelby, MS National Guard",
  "Sewage Treatment Project, Pine Belt Airport",
  "Hattiesburg-Laurel Regional Airport",
  "Carson Water System Improvements, Phase I, Jeff Davis County",
  "Pumping Station Rehabilitation, Cooper Power Systems, Lamar County BOS",
  "Fire Protection Water System, Russell Utilities",
  "M&M Water Association Waterline Relocation Project",
  "Petal Family Y",
  "Site Utilities for Petal Walmart",
  "Sewer Main Addition Psychiatric Hospital Site, City of Purvis",
  "Bellcrest Mobile Home Village Phase II, Pat Riley",
  "Nordan Smith Welding Generation, Production & Distribution Complex",
  "West Lake Manor Second Addition, Lamar Park Water Association",
  "Sanitary Sewer & Collection System, Timberton Golf Club",
  "Oak Hill Subdivision Phase I",
  "Forrest General Hospital — ED and ICU Addition",
];

export const NAV_LINKS = [
  { label: "About", href: "#about" },
  { label: "Services", href: "#services" },
  { label: "Projects", href: "#projects" },
  { label: "Testimonials", href: "#testimonials" },
  { label: "Careers", href: "#careers" },
  { label: "Contact", href: "#contact" },
];
